services:
  myapp:
    container_name: facturas-backend
    image: facturas-backend
    build:
      context: .
      #dockerfile: Dockerfile
    ports:
      - "8585:8585"
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: manusl2908
      POSTGRES_PASSWORD: Chismosear01-
      POSTGRES_DB: facturas
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
